logging:
  charset:
    console: UTF-8
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-dd-MM-yyyy HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%t]){faint} %clr(%logger{0}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    dateformat: "dd-MM-yyyy HH:mm:ss.SSS"
spring:
  application:
    name: argus
  main:
    log-startup-info: true
server:
  port: 3103

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
discovery:
  namespaces:
    - kube-prometheus-stack
    - loki
  probe:
    timeout: 3s
    retry-count: 2
  cache:
    ttl: 5m
  port-forward:
    enabled: true