spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.29.2:5432/argus
    username: argus
    password: argus
totp:
  issuer: "[dev] Argus Telegram Agent"
github:
  app:
    id: Iv23liRlrYyxMZRwgTuI
    private-key-path: /home/akira/code/argus/homelab-datnvm.2026-07-04.private-key.pem
    token-refresh-margin: 10m
    secret: ${GITHUB_APP_SECRET}