apiVersion: v1
kind: Service
metadata:
  name: argus
  namespace: argus
  labels:
    app.kubernetes.io/name: argus
spec:
  selector:
    app.kubernetes.io/name: argus
  ports:
    - name: http
      port: 3103
      targetPort: http
  type: ClusterIP
